spring.application.name=demowuri
spring.datasource.url=jdbc:postgresql://localhost:5432/fid
spring.datasource.username=postgres
spring.datasource.password=2885351
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
jwt.secret=U2FsdGVkX1+LHSd97iwLHMKJt0HZ5ZubIQBqT+33WBGwS80z/g77wfgkSRz98dfV7ghjWEiu7fwHYdQ4ZwYjsHD3szVJPQY8S0gAFoQv0Ro=
logging.level.org.springframework.security=DEBUG
# Dossier de stockage des photos
app.photos.dir=photos
jwt.qr.expiration.minutes=5


# Taille max upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=5MB

server.error.include-message=always
server.error.include-stacktrace=always

# ─── WhatsApp Business Cloud API (Meta) ───────────────────────────────────────
# Récupérer sur https://developers.facebook.com > votre app > WhatsApp > API Setup
whatsapp.api.url=https://graph.facebook.com/v25.0
whatsapp.phone-number-id=980338345172944
whatsapp.access-token=EAANj0UcvyzgBRE1CjvSy9McX1z5gx7DWqvle7RePHR7ajzZCkdDbEvtuuigBHYiZBZBJvZC9E1QiF4z3vQ0NIrZAps8kmeAlSZADiCvTIu96Ybbxxym2qBnxpbsUs80QWWGG7NW9iZAyNyu4AZCQMgjFDjrHHZBZAomzRxZBJevNZC4XX8JYejYY2d5zZCUkQe1sJDpp3TpY7DivDIGzMZBXD3en38ybWG8qyb525ROugaf66AMw0gWOW0VCZBKDJK3xZBGFNtP43HFwnQSmtdLHGvJ7GUCj
whatsapp.country-code=226
# Template sandbox (hello_world) — remplacer par ton template OTP en production
whatsapp.template-name=hello_world
whatsapp.template-lang=en_US



